name = "LHEF"
uuid = "4dba1963-fdf1-41a9-b228-d13b5fa087e3"
authors = ["Jerry Ling <proton@jling.dev>"]
version = "0.1.0"

[deps]
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
LorentzVectors = "3f54b04b-17fc-5cd4-9758-90c048d965e3"

[compat]
julia = "^1.3"
