name = "LHEF"
uuid = "4dba1963-fdf1-41a9-b228-d13b5fa087e3"
authors = ["Jerry Ling <proton@jling.dev>"]
version = "0.3.0"

[deps]
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[compat]
EzXML = "^1.1.0"
julia = "^1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
